name: Run OI Updates from NSE.

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests pymongo decouple
      - name: Run script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
        run: |
          python get_data.py
      - name: Commit if any new files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated files for ${{ steps.date.outputs.date }}" -a
      - name: push changes
        uses: |
          ad-m/github-push-action@v0.6.0
        with: |
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
